pastebin-project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('pastebin.urls')),
    path('admin/', admin.site.urls),
]

pastebin/urls.py
from django.urls import path

from . import views

app_name = 'pastebin'
urlpatterns = [
	path('', views.index, name='index'),
	path('create/', views.create, name='create'),
	path('latest/', views.latest, name='latest'),
	path('<int:paste_id>/', views.details, name='details'),
	path('<int:paste_id>/dl', views.download, name='download'),
	path('<int:paste_id>/raw', views.raw, name='raw'),
]

pastebin/models.py
import datetime

from django.db import models
from django.utils import timezone


class Paste(models.Model):
	paste_title = models.CharField(max_length=100)
	paste_code = models.TextField()  # max paste size is 4kb
	paste_format = models.CharField(max_length=20)  # the paste is written in... ...python, bash, lua, etc
	pub_date = models.DateTimeField('date published')
	# paste_expiration = models.DateTimeField()  # datetime.timedelta might be helpful
	# paste_exposure = models.CharField(max_length=20)  # public, private, unlisted

	def __str__(self):
		return self.paste_title

pastebin/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from django.urls import reverse

from .models import Paste


def index(request):
	return render(request, 'pastebin/index.html')


def details(request, paste_id):
	paste = get_object_or_404(Paste, pk=paste_id)
	return render(request, 'pastebin/details.html', {'paste': paste})


def raw(request, paste_id):
	paste = get_object_or_404(Paste, pk=paste_id)
	return HttpResponse(paste.paste_code, content_type='text/plain')


def latest(request, n=20):
	latest_paste_list = Paste.objects.order_by('-pub_date')[:n]
	return render(request, 'pastebin/latest.html', {'latest_paste_list': latest_paste_list})


def create(request):
	try:
		paste_title = request.POST.get('paste_title', 'Untitled')
		paste_format = request.POST.get('paste_format', 'Plain Text')
		paste_code = request.POST['paste_code']
		if len(paste_code) == 0:
			raise ValueError
	except (KeyError, ValueError):
		# Redisplay the index page with error message.
		return render(request, 'pastebin/index.html', {
			'error_message': "Empty paste are not allowed.",
		})
	else:
		paste = Paste(paste_title=paste_title, paste_code=paste_code, paste_format=paste_format, pub_date=timezone.now())
		paste.save()
		# Always return an HttpResponseRedirect after successfully dealing
		# with POST data. This prevents data from being posted twice if a
		# user hits the Back button.
		return HttpResponseRedirect(reverse('pastebin:details', args=(paste.id,)))


def download(request, paste_id):
	# https://stackoverflow.com/questions/1156246/having-django-serve-downloadable-files
	# https://stackoverflow.com/questions/36392510/django-download-a-file
	paste = get_object_or_404(Paste, pk=paste_id)
	response = HttpResponse(paste.paste_code, content_type='application/force-download')
	response['Content-Disposition'] = 'inline; filename=%s.txt' % paste.paste_title
	response['Content-Length'] = len(paste.paste_code)
	return response

pastebin/templates/pastebin/details.html
<!DOCTYPE html>
<html>
<head>
	<title>{{ paste.paste_title }}</title>
	<style type="text/css">
	body {
	    color: #566b78;
	    font-family: Arial, Helvetica, sans-serif;
	    line-height: 1.5;
	    margin: 0 auto;
	    max-width: 50em;
	    padding: 4em 1em;
	}
	h2 {
	    margin-top: 1em;
	    padding-top: 1em;
	}
	h1, h2, strong {
	    color: #333;
	}
	code, pre {
	    background: #f5f7f9;
	    color: #a7adba;
	}
	code {
	    padding: 2px 4px;
	    vertical-align: text-bottom;
	}
	pre {
	    border-bottom: 1px solid #d8dee9;
	    border-left: 2px solid #69c;
	}
	a {
	    color: #e81c4f;
	}
	</style>
</head>
<body>
<h1>{{ paste.paste_title }}</h1>
Paste Format: {{ paste.paste_format }}<br>
Date Created: {{ paste.pub_date }}<br>
<button onclick="location.href='{% url 'pastebin:download' paste.id %}';">Download</button>
<button onclick="location.href='{% url 'pastebin:raw' paste.id %}';">Raw</button>
<br>
<pre><code>{{ paste.paste_code }}</code></pre>
</body>
</html>

pastebin/templates/pastebin/index.html
<h1>Advik's PASTEBIN</h1>
<a href="{% url 'pastebin:latest' %}">latest</a>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<h2>New Paste</h2>
<form action="{% url 'pastebin:create' %}" method="post">
{% csrf_token %}
	<textarea name='paste_code' style='width: 100%;height: 250px;'></textarea>
	Paste Name/Title: <input type="text" name="paste_title"><br>
	Syntax Highlighting: <select name="paste_format"><option value="Plain Text">Plain Text</option></select><br>
	<input type="submit" value="Create New Paste">
</form>

pastebin/templates/pastebin/latest.html
{% if latest_paste_list %}
	<ul>
	{% for paste in latest_paste_list %}
		<li><a href="{% url 'pastebin:details' paste.id %}">{{ paste.paste_title }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No polls are available.</p>
{% endif %}